# Generated by Django 2.0 on 2017-12-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='due_weekday',
        ),
        migrations.AlterField(
            model_name='expense',
            name='periodicity',
            field=models.CharField(choices=[('MO', 'Monthly'), ('BI', 'Bimonthly'), ('AN', 'Annually')], default='MO', max_length=2),
        ),
    ]
