# Generated by Django 2.0 on 2018-01-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_transaction_expense'),
        ('budget', '0002_auto_20171231_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
