from core.views.list_account_view import ListAccountView
from core.views.create_account_view import CreateAccountView
from core.views.update_account_view import UpdateAccountView
from core.views.update_inbox_account_view import UpdateInboxAccountView
from core.views.list_bucket_view import ListBucketView
from core.views.create_bucket_view import CreateBucketView
from core.views.update_bucket_view import UpdateBucketView
from core.views.create_transfer_to_bucket_view import CreateTransferToBucketView
from core.views.create_debit_transaction_view import CreateDebitTransactionView
from core.views.update_debit_transaction_view import UpdateDebitTransactionView
from core.views.create_credit_transaction_view import CreateCreditTransactionView
from core.views.update_credit_transaction_view import UpdateCreditTransactionView

from core.views.create_transfer_to_user_view import new_transfer_to_user
from core.views.create_transfer_to_account_view import new_transfer_to_account
from core.views.update_transaction_view import update_transaction
from core.views.dashboard_view import dashboard
