language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python manage.py test --settings=prudget.settings.local

deploy:
  provider: heroku
  api_key: $DEPLOY_API_KEY
  all_branches: true
