language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

env:
  - DATABASE_URL=sqlite:////db.sqlite3

script:
  - python manage.py collectstatic
  - python manage.py test

branches:
  only:
    - master

before_deploy:
  - zappa package production -o prudget-release.zip

deploy:
  provider: lambda
  function_name: "prudget-production"
  region: "us-east-1"
  role: $ROLE_DEPLOY
  handler_name: "lambda_handler"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  runtime: "python3.6"
  module_name: "handler"
  skip_cleanup: true
  zip: prudget-release.zip
  timeout: 15
  memory_size: 512
