language: python
python:
  - "3.6"

env:
  - DJANGO_SETTINGS_MODULE=prudget.settings.local

install:
  - pip install -r requirements.txt

script:
  - python manage.py collectstatic
  - python manage.py test

deploy:
  provider: heroku
  api_key: $DEPLOY_API_KEY
