language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

env:
  - DATABASE_URL=sqlite:////db.sqlite3

script:
  - python manage.py collectstatic --noinput
  - python manage.py test

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key: $DEPLOY_API_KEY
