version: '3'

services:
  postgres.prudget.local:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'prudget_password'
      POSTGRES_USER: 'prudget'
      POSTGRES_DB: 'prudget'
    volumes:
      - ./database:/var/lib/postgresql/data
  app.prudget.local:
    build: .
    command: ./init-dev.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres.prudget.local
    environment:
      DATABASE_URL: 'postgres://prudget:prudget_password@postgres.prudget.local/prudget'
  web.prudget.local:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./prudget/staticfiles:/data/staticfiles
    depends_on:
      - app.prudget.local
