version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py collectstatic --noinput
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - add_ssh_keys:
          fingerprints:
            - "fc:f7:3d:42:46:04:3e:3d:b2:4f:3b:76:49:1a:c0:0c"

      - run:
          name: Deploy to Bathala
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_DEPLOY_USER@$SSH_DEPLOY_HOST -p $SSH_DEPLOY_PORT "$DEPLOY_COMMAND"
