# Generated by Django 2.0 on 2018-01-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference_date',
        ),
    ]
