# Generated by Django 2.0 on 2017-12-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_bucketvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='show_balance',
            field=models.BooleanField(default=False),
        ),
    ]
