# Generated by Django 2.0 on 2017-12-31 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('transactions', '0005_bucket_show_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Expense'),
        ),
    ]
