# Generated by Django 2.0 on 2018-01-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
