# Generated by Django 2.0 on 2018-01-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_reference_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='expense',
        ),
    ]
