# Generated by Django 2.0 on 2018-01-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_transaction_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketvalue',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='bucketvalue',
            name='owner',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.Account'),
        ),
        migrations.DeleteModel(
            name='BucketValue',
        ),
    ]
