# Generated by Django 2.0 on 2018-01-05 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_transaction_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
