# Generated by Django 2.0 on 2018-01-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20180104_2207'),
        ('transactions', '0009_auto_20180104_2314'),
    ]

    operations = [
    ]
