# Generated by Django 2.0 on 2018-01-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_merge_20180105_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='show_balance',
        ),
    ]
